#!/bin/bash

IMAGE_NAME="docker-symfony"
CONTAINER_TEST="docker-symfony-test"

if [ -z $1 ]; then
    echo -e "Supported arguments:
        * docker [build|test|cmd]
        * help
    "
elif [ "$1" == "help" ]; then
    echo "docker rmi $IMAGE_NAME"
    echo "docker inspect $CONTAINER_TEST"
    echo "docker logs $CONTAINER_TEST"

elif [ "$1" == "docker" ]; then
    if [ -z $2 ]; then
        echo -e "Available options:
            * build
            * test
            * ssh
        "
    elif [ "$2" == "build" ]; then
       if docker ps -a | grep $CONTAINER_TEST; then
            echo "Removing current container..."
            docker rm -f $CONTAINER_TEST
       fi

       docker rmi -f $(docker images -f "dangling=true" -q)
       docker rmi -f $IMAGE_NAME
       docker build -t=$IMAGE_NAME .

    elif [ "$2" == "test" ]; then
        if docker ps -a | grep $CONTAINER_TEST; then
            echo "Removing current container..."
            docker rm -f $CONTAINER_TEST
        fi
        docker run -d --name $CONTAINER_TEST -v `pwd`/store:/data/www -p 9999:80 $IMAGE_NAME
    elif [ "$2" == "ssh" ]; then
        docker exec -it $CONTAINER_TEST bash
    fi
fi