#!/bin/bash

IMAGE_NAME="devhoanggia/nginx"
CONTAINER_NAME="nginx:server"

PORT_HOST=9999
DB_DIRECTORY="/Users/lap00344/MyProject/database"

if [ -z $1 ]; then
    echo -e "Supported arguments:
        * help
        * docker [start|ssh|cmd|compose]
    "
elif [ "$1" == "help" ]; then
    echo "Docker config"
    echo "Container: $CONTAINER_NAME"
    echo "DB directory: $DB_DIRECTORY"
    echo "Port host: $PORT_HOST"
    echo
    echo "docker rmi IMAGES"
    echo "docker inspect $CONTAINER_NAME"
    echo "docker logs $CONTAINER_NAME"

elif [ "$1" == "init" ]; then
    echo "Initiating application..."
    #chmod -R 777 app/cache
elif [ "$1" == "docker" ]; then
    if [ -z $2 ]; then
        echo -e "Available options:
            * start
            * ssh
            * cmd
            * compose
        "
    elif [ "$2" == "start" ]; then
        if docker ps -a | grep $CONTAINER_NAME; then
            echo "Removing current container $CONTAINER_NAME"
            docker rm -f $CONTAINER_NAME
        fi

        if docker ps -a | grep db; then
            echo "Removing current container db"
            docker rm -f db
        fi

        echo "Creating container mysql..."
        docker run --name db -d -p 8888:3306 -v $DB_DIRECTORY:/store/db devhoanggia/docker-mysql

        echo "Creating container server..."
        docker run --name $CONTAINER_NAME -d -p $PORT_HOST:80 -v `pwd`:/data/www --link db:mysql $IMAGE_NAME

    elif [ "$2" == "ssh" ]; then
        docker exec -it $CONTAINER_NAME bash
    fi
else
    if docker ps -a | grep -qs $CONTAINER_NAME; then
        docker exec -it $CONTAINER_NAME bash -c "cd /data/www; $*"
    else
        echo "Please start the container first!"
        exit
    fi
fi